# Generated by Django 3.1.7 on 2021-04-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('viewed', models.DateTimeField(blank=True, null=True, verbose_name='Viewed')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='Full name')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('birthdate', models.DateField(verbose_name='Bithdate')),
                ('description', models.CharField(blank=True, max_length=400, verbose_name='description')),
                ('profile_picture', models.ImageField(blank=True, upload_to='', verbose_name='Profiel Picture')),
                ('nickname', models.CharField(max_length=20, verbose_name='Nickname')),
                ('created_at', models.DateTimeField(editable=False)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
