# Generated by Django 3.1.7 on 2021-04-25 07:46

import chatBackend.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatBackend', '0003_auto_20210422_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='person_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='persons',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='persons',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=chatBackend.models.get_upload_path, verbose_name='Profiel Picture'),
        ),
    ]
