# Generated by Django 3.1.7 on 2021-04-25 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chatBackend', '0004_auto_20210425_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persons',
            name='person_uuid',
        ),
        migrations.AlterField(
            model_name='persons',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
